// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htbfywqpoxwnsmbcnjlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0YmZ5d3Fwb3h3bnNtYmNuamx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NjcwNjYsImV4cCI6MjA1OTE0MzA2Nn0.7uYBSsqO_p2YGXUGYAonHYqkXgmLr_BsXE6KUXg2y8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);